/**
 * Curated World Currencies with Country Names, Codes, and Symbols.
 * Israel (ILS / ₪) is strictly excluded per system requirements.
 */

export const CURRENCY_LIST = [
    { code: "AFN", name: "Afghan Afghani", symbol: "؋", country: "Afghanistan" },
    { code: "ALL", name: "Albanian Lek", symbol: "L", country: "Albania" },
    { code: "DZD", name: "Algerian Dinar", symbol: "د.ج", country: "Algeria" },
    { code: "AOA", name: "Angolan Kwanza", symbol: "Kz", country: "Angola" },
    { code: "AMD", name: "Armenian Dram", symbol: "֏", country: "Armenia" },
    { code: "AWG", name: "Aruban Florin", symbol: "ƒ", country: "Aruba" },
    { code: "AUD", name: "Australian Dollar", symbol: "$", country: "Australia" },
    { code: "AZN", name: "Azerbaijani Manat", symbol: "₼", country: "Azerbaijan" },
    { code: "BHD", name: "Bahraini Dinar", symbol: "ب.د", country: "Bahrain" },
    { code: "BDT", name: "Bangladeshi Taka", symbol: "৳", country: "Bangladesh" },
    { code: "BYN", name: "Belarusian Ruble", symbol: "Br", country: "Belarus" },
    { code: "BZD", name: "Belize Dollar", symbol: "BZ$", country: "Belize" },
    { code: "BTN", name: "Bhutanese Ngultrum", symbol: "Nu.", country: "Bhutan" },
    { code: "BOB", name: "Bolivian Boliviano", symbol: "Bs.", country: "Bolivia" },
    { code: "BWP", name: "Botswana Pula", symbol: "P", country: "Botswana" },
    { code: "BRL", name: "Brazilian Real", symbol: "R$", country: "Brazil" },
    { code: "GBP", name: "British Pound", symbol: "£", country: "United Kingdom" },
    { code: "BGN", name: "Bulgarian Lev", symbol: "лв", country: "Bulgaria" },
    { code: "BIF", name: "Burundian Franc", symbol: "FBu", country: "Burundi" },
    { code: "KHR", name: "Cambodian Riel", symbol: "៛", country: "Cambodia" },
    { code: "CAD", name: "Canadian Dollar", symbol: "$", country: "Canada" },
    { code: "CNY", name: "Chinese Yuan", symbol: "¥", country: "China" },
    { code: "CRC", name: "Costa Rican Colón", symbol: "₡", country: "Costa Rica" },
    { code: "HRK", name: "Croatian Kuna", symbol: "kn", country: "Croatia" },
    { code: "CZK", name: "Czech Koruna", symbol: "Kč", country: "Czech Republic" },
    { code: "DKK", name: "Danish Krone", symbol: "kr", country: "Denmark" },
    { code: "DOP", name: "Dominican Peso", symbol: "RD$", country: "Dominican Republic" },
    { code: "EGP", name: "Egyptian Pound", symbol: "E£", country: "Egypt" },
    { code: "EUR", name: "Euro", symbol: "€", country: "European Union" },
    { code: "GHS", name: "Ghanaian Cedi", symbol: "₵", country: "Ghana" },
    { code: "GTQ", name: "Guatemalan Quetzal", symbol: "Q", country: "Guatemala" },
    { code: "HNL", name: "Honduran Lempira", symbol: "L", country: "Honduras" },
    { code: "HUF", name: "Hungarian Forint", symbol: "Ft", country: "Hungary" },
    { code: "ISK", name: "Icelandic Króna", symbol: "kr", country: "Iceland" },
    { code: "INR", name: "Indian Rupee", symbol: "₹", country: "India" },
    { code: "IDR", name: "Indonesian Rupiah", symbol: "Rp", country: "Indonesia" },
    { code: "IRR", name: "Iranian Rial", symbol: "﷼", country: "Iran" },
    { code: "IQD", name: "Iraqi Dinar", symbol: "ع.د", country: "Iraq" },
    { code: "JMD", name: "Jamaican Dollar", symbol: "J$", country: "Jamaica" },
    { code: "JPY", name: "Japanese Yen", symbol: "¥", country: "Japan" },
    { code: "JOD", name: "Jordanian Dinar", symbol: "د.ا", country: "Jordan" },
    { code: "KZT", name: "Kazakhstani Tenge", symbol: "₸", country: "Kazakhstan" },
    { code: "KES", name: "Kenyan Shilling", symbol: "Ksh", country: "Kenya" },
    { code: "KWD", name: "Kuwaiti Dinar", symbol: "د.ك", country: "Kuwait" },
    { code: "LAK", name: "Lao Kip", symbol: "₭", country: "Laos" },
    { code: "LBP", name: "Lebanese Pound", symbol: "ل.ل", country: "Lebanon" },
    { code: "MYR", name: "Malaysian Ringgit", symbol: "RM", country: "Malaysia" },
    { code: "MXN", name: "Mexican Peso", symbol: "$", country: "Mexico" },
    { code: "MAD", name: "Moroccan Dirham", symbol: "د.م.", country: "Morocco" },
    { code: "NZD", name: "New Zealand Dollar", symbol: "$", country: "New Zealand" },
    { code: "NGN", name: "Nigerian Naira", symbol: "₦", country: "Nigeria" },
    { code: "NOK", name: "Norwegian Krone", symbol: "kr", country: "Norway" },
    { code: "OMR", name: "Omani Rial", symbol: "ر.ع.", country: "Oman" },
    { code: "PKR", name: "Pakistani Rupee", symbol: "₨", country: "Pakistan" },
    { code: "PEN", name: "Peruvian Sol", symbol: "S/", country: "Peru" },
    { code: "PHP", name: "Philippine Peso", symbol: "₱", country: "Philippines" },
    { code: "PLN", name: "Polish Złoty", symbol: "zł", country: "Poland" },
    { code: "QAR", name: "Qatari Riyal", symbol: "ر.ق", country: "Qatar" },
    { code: "RON", name: "Romanian Leu", symbol: "lei", country: "Romania" },
    { code: "RUB", name: "Russian Ruble", symbol: "₽", country: "Russia" },
    { code: "SAR", name: "Saudi Riyal", symbol: "ر.س", country: "Saudi Arabia" },
    { code: "SGD", name: "Singapore Dollar", symbol: "S$", country: "Singapore" },
    { code: "ZAR", name: "South African Rand", symbol: "R", country: "South Africa" },
    { code: "SEK", name: "Swedish Krona", symbol: "kr", country: "Sweden" },
    { code: "CHF", name: "Swiss Franc", symbol: "Fr", country: "Switzerland" },
    { code: "THB", name: "Thai Baht", symbol: "฿", country: "Thailand" },
    { code: "TRY", name: "Turkish Lira", symbol: "₺", country: "Turkey" },
    { code: "AED", name: "UAE Dirham", symbol: "د.إ", country: "United Arab Emirates" },
    { code: "USD", name: "United States Dollar", symbol: "$", country: "United States" },
    { code: "VND", name: "Vietnamese Đồng", symbol: "₫", country: "Vietnam" },
    { code: "YER", name: "Yemeni Rial", symbol: "﷼", country: "Yemen" }
].sort((a, b) => a.name.localeCompare(b.name));
