/**
 * Curated World Currencies with Country Names, Flags, Codes, and Symbols.
 * Israel (ILS / ₪) is strictly excluded per system requirements.
 */

export const CURRENCY_LIST = [
    { code: "AFN", name: "Afghan Afghani", symbol: "؋", flag: "🇦🇫", country: "Afghanistan" },
    { code: "ALL", name: "Albanian Lek", symbol: "L", flag: "🇦🇱", country: "Albania" },
    { code: "DZD", name: "Algerian Dinar", symbol: "د.ج", flag: "🇩🇿", country: "Algeria" },
    { code: "AOA", name: "Angolan Kwanza", symbol: "Kz", flag: "🇦🇴", country: "Angola" },
    { code: "AMD", name: "Armenian Dram", symbol: "֏", flag: "🇦🇲", country: "Armenia" },
    { code: "AWG", name: "Aruban Florin", symbol: "ƒ", flag: "🇦🇼", country: "Aruba" },
    { code: "AUD", name: "Australian Dollar", symbol: "$", flag: "🇦🇺", country: "Australia" },
    { code: "AZN", name: "Azerbaijani Manat", symbol: "₼", flag: "🇦🇿", country: "Azerbaijan" },
    { code: "BHD", name: "Bahraini Dinar", symbol: "ب.د", flag: "🇧🇭", country: "Bahrain" },
    { code: "BDT", name: "Bangladeshi Taka", symbol: "৳", flag: "🇧🇩", country: "Bangladesh" },
    { code: "BYN", name: "Belarusian Ruble", symbol: "Br", flag: "🇧🇾", country: "Belarus" },
    { code: "BZD", name: "Belize Dollar", symbol: "BZ$", flag: "🇧🇿", country: "Belize" },
    { code: "BTN", name: "Bhutanese Ngultrum", symbol: "Nu.", flag: "🇧🇹", country: "Bhutan" },
    { code: "BOB", name: "Bolivian Boliviano", symbol: "Bs.", flag: "🇧🇴", country: "Bolivia" },
    { code: "BWP", name: "Botswana Pula", symbol: "P", flag: "🇧🇼", country: "Botswana" },
    { code: "BRL", name: "Brazilian Real", symbol: "R$", flag: "🇧🇷", country: "Brazil" },
    { code: "GBP", name: "British Pound", symbol: "£", flag: "🇬🇧", country: "United Kingdom" },
    { code: "BGN", name: "Bulgarian Lev", symbol: "лв", flag: "🇧🇬", country: "Bulgaria" },
    { code: "BIF", name: "Burundian Franc", symbol: "FBu", flag: "🇧🇮", country: "Burundi" },
    { code: "KHR", name: "Cambodian Riel", symbol: "៛", flag: "🇰🇭", country: "Cambodia" },
    { code: "CAD", name: "Canadian Dollar", symbol: "$", flag: "🇨🇦", country: "Canada" },
    { code: "CNY", name: "Chinese Yuan", symbol: "¥", flag: "🇨🇳", country: "China" },
    { code: "CRC", name: "Costa Rican Colón", symbol: "₡", flag: "🇨🇷", country: "Costa Rica" },
    { code: "HRK", name: "Croatian Kuna", symbol: "kn", flag: "🇭🇷", country: "Croatia" },
    { code: "CZK", name: "Czech Koruna", symbol: "Kč", flag: "🇨🇿", country: "Czech Republic" },
    { code: "DKK", name: "Danish Krone", symbol: "kr", flag: "🇩🇰", country: "Denmark" },
    { code: "DOP", name: "Dominican Peso", symbol: "RD$", flag: "🇩🇴", country: "Dominican Republic" },
    { code: "EGP", name: "Egyptian Pound", symbol: "E£", flag: "🇪🇬", country: "Egypt" },
    { code: "EUR", name: "Euro", symbol: "€", flag: "🇪🇺", country: "European Union" },
    { code: "GHS", name: "Ghanaian Cedi", symbol: "₵", flag: "🇬🇭", country: "Ghana" },
    { code: "GTQ", name: "Guatemalan Quetzal", symbol: "Q", flag: "🇬🇹", country: "Guatemala" },
    { code: "HNL", name: "Honduran Lempira", symbol: "L", flag: "🇭🇳", country: "Honduras" },
    { code: "HUF", name: "Hungarian Forint", symbol: "Ft", flag: "🇭🇺", country: "Hungary" },
    { code: "ISK", name: "Icelandic Króna", symbol: "kr", flag: "🇮🇸", country: "Iceland" },
    { code: "INR", name: "Indian Rupee", symbol: "₹", flag: "🇮🇳", country: "India" },
    { code: "IDR", name: "Indonesian Rupiah", symbol: "Rp", flag: "🇮🇩", country: "Indonesia" },
    { code: "IRR", name: "Iranian Rial", symbol: "﷼", flag: "🇮🇷", country: "Iran" },
    { code: "IQD", name: "Iraqi Dinar", symbol: "ع.د", flag: "🇮🇶", country: "Iraq" },
    { code: "JMD", name: "Jamaican Dollar", symbol: "J$", flag: "🇯🇲", country: "Jamaica" },
    { code: "JPY", name: "Japanese Yen", symbol: "¥", flag: "🇯🇵", country: "Japan" },
    { code: "JOD", name: "Jordanian Dinar", symbol: "د.ا", flag: "🇯🇴", country: "Jordan" },
    { code: "KZT", name: "Kazakhstani Tenge", symbol: "₸", flag: "🇰🇿", country: "Kazakhstan" },
    { code: "KES", name: "Kenyan Shilling", symbol: "Ksh", flag: "🇰🇪", country: "Kenya" },
    { code: "KWD", name: "Kuwaiti Dinar", symbol: "د.ك", flag: "🇰🇼", country: "Kuwait" },
    { code: "LAK", name: "Lao Kip", symbol: "₭", flag: "🇱🇦", country: "Laos" },
    { code: "LBP", name: "Lebanese Pound", symbol: "ل.ل", flag: "🇱🇧", country: "Lebanon" },
    { code: "MYR", name: "Malaysian Ringgit", symbol: "RM", flag: "🇲🇾", country: "Malaysia" },
    { code: "MXN", name: "Mexican Peso", symbol: "$", flag: "🇲🇽", country: "Mexico" },
    { code: "MAD", name: "Moroccan Dirham", symbol: "د.م.", flag: "🇲🇦", country: "Morocco" },
    { code: "NZD", name: "New Zealand Dollar", symbol: "$", flag: "🇳🇿", country: "New Zealand" },
    { code: "NGN", name: "Nigerian Naira", symbol: "₦", flag: "🇳🇬", country: "Nigeria" },
    { code: "NOK", name: "Norwegian Krone", symbol: "kr", flag: "🇳🇴", country: "Norway" },
    { code: "OMR", name: "Omani Rial", symbol: "ر.ع.", flag: "🇴🇲", country: "Oman" },
    { code: "PKR", name: "Pakistani Rupee", symbol: "₨", flag: "🇵🇰", country: "Pakistan" },
    { code: "PEN", name: "Peruvian Sol", symbol: "S/", flag: "🇵🇪", country: "Peru" },
    { code: "PHP", name: "Philippine Peso", symbol: "₱", flag: "🇵🇭", country: "Philippines" },
    { code: "PLN", name: "Polish Złoty", symbol: "zł", flag: "🇵🇱", country: "Poland" },
    { code: "QAR", name: "Qatari Riyal", symbol: "ر.ق", flag: "🇶🇦", country: "Qatar" },
    { code: "RON", name: "Romanian Leu", symbol: "lei", flag: "🇷🇴", country: "Romania" },
    { code: "RUB", name: "Russian Ruble", symbol: "₽", flag: "🇷🇺", country: "Russia" },
    { code: "SAR", name: "Saudi Riyal", symbol: "ر.س", flag: "🇸🇦", country: "Saudi Arabia" },
    { code: "SGD", name: "Singapore Dollar", symbol: "S$", flag: "🇸🇬", country: "Singapore" },
    { code: "ZAR", name: "South African Rand", symbol: "R", flag: "🇿🇦", country: "South Africa" },
    { code: "SEK", name: "Swedish Krona", symbol: "kr", flag: "🇸🇪", country: "Sweden" },
    { code: "CHF", name: "Swiss Franc", symbol: "Fr", flag: "🇨🇭", country: "Switzerland" },
    { code: "THB", name: "Thai Baht", symbol: "฿", flag: "🇹🇭", country: "Thailand" },
    { code: "TRY", name: "Turkish Lira", symbol: "₺", flag: "🇹🇷", country: "Turkey" },
    { code: "AED", name: "UAE Dirham", symbol: "د.إ", flag: "🇦🇪", country: "United Arab Emirates" },
    { code: "USD", name: "United States Dollar", symbol: "$", flag: "🇺🇸", country: "United States" },
    { code: "VND", name: "Vietnamese Đồng", symbol: "₫", flag: "🇻🇳", country: "Vietnam" },
    { code: "YER", name: "Yemeni Rial", symbol: "﷼", flag: "🇾🇪", country: "Yemen" }
].sort((a, b) => a.name.localeCompare(b.name));
